export const ROLES = {
  FARMER: 'FARMER',
  PROCUREMENT_OFFICER: 'PROCUREMENT_OFFICER',
  CENTRE_MANAGER: 'CENTRE_MANAGER',
  DISTRICT_OFFICER: 'DISTRICT_OFFICER',
  SUPER_ADMIN: 'SUPER_ADMIN'
} as const;

export type UserRole = keyof typeof ROLES;
