const ROLES = {
  FARMER: 'FARMER',
  CENTER_OPERATOR: 'CENTER_OPERATOR',
  PROCUREMENT_OFFICER: 'CENTER_OPERATOR',
  CENTRE_MANAGER: 'CENTRE_MANAGER',
  CENTER_MANAGER: 'CENTER_MANAGER',
  DISTRICT_ADMIN: 'DISTRICT_ADMIN',
  DISTRICT_OFFICER: 'DISTRICT_ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN'
};

const ALL_ROLES = [
  'FARMER',
  'CENTER_OPERATOR',
  'PROCUREMENT_OFFICER',
  'CENTRE_MANAGER',
  'CENTER_MANAGER',
  'DISTRICT_ADMIN',
  'DISTRICT_OFFICER',
  'SUPER_ADMIN'
];

module.exports = {
  ROLES,
  ALL_ROLES
};
