const USER_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
  ACTIVE: 'APPROVED',
  INACTIVE: 'SUSPENDED'
};

const CENTRE_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  MAINTENANCE: 'MAINTENANCE'
};

const BOOKING_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
  RESCHEDULED: 'RESCHEDULED'
};

const TOKEN_STATUS = {
  WAITING: 'WAITING',
  CALLED: 'CALLED',
  ARRIVED: 'ARRIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  ABSENT: 'ABSENT',
  CANCELLED: 'CANCELLED',
  RESCHEDULED: 'RESCHEDULED'
};

const PROCUREMENT_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  ARRIVED: 'ARRIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const PAYMENT_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  PAID: 'PAID',
  FAILED: 'FAILED'
};

const COUNTER_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  MAINTENANCE: 'MAINTENANCE'
};

const ASSIGNMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

module.exports = {
  USER_STATUS,
  CENTRE_STATUS,
  BOOKING_STATUS,
  TOKEN_STATUS,
  PROCUREMENT_STATUS,
  PAYMENT_STATUS,
  COUNTER_STATUS,
  ASSIGNMENT_STATUS
};
